services:
  - type: web
    name: django-starter
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-starter-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: django-starter-redis
          property: connectionString
      - key: ALLOWED_HOSTS
        value: django-starter.onrender.com
      - key: USE_HTTPS_IN_ABSOLUTE_URLS
        value: True
      - key: GUNICORN_WORKERS
        value: 3

databases:
  - name: django-starter-db
    databaseName: django_starter
    user: django_starter

redis:
  - name: django-starter-redis
    region: oregon
    plan: free
    maxmemoryPolicy: allkeys-lru
