# Generated by Django 6.0.5 on 2026-07-18 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for group identification', max_length=7)),
            ],
            options={
                'verbose_name': 'Device Group',
                'verbose_name_plural': 'Device Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ssid', models.CharField(default='NetVista-WiFi', max_length=100)),
                ('password', models.CharField(default='securepassword123', max_length=100)),
                ('guest_network_enabled', models.BooleanField(default=False)),
                ('guest_ssid', models.CharField(default='NetVista-Guest', max_length=100)),
                ('guest_password', models.CharField(blank=True, max_length=100)),
                ('security_mode', models.CharField(choices=[('wpa2', 'WPA2'), ('wpa3', 'WPA3'), ('wep', 'WEP')], default='wpa2', max_length=20)),
                ('wifi_channel', models.IntegerField(default=6, help_text='WiFi channel (1-11)')),
                ('bandwidth_limit_mbps', models.IntegerField(default=1000, help_text='Bandwidth limit in Mbps')),
                ('dhcp_enabled', models.BooleanField(default=True)),
                ('dhcp_start_ip', models.CharField(default='192.168.1.100', max_length=15)),
                ('dhcp_end_ip', models.CharField(default='192.168.1.200', max_length=15)),
                ('dns_primary', models.CharField(default='8.8.8.8', max_length=15)),
                ('dns_secondary', models.CharField(default='8.8.4.4', max_length=15)),
                ('lan_ip', models.CharField(default='192.168.1.1', max_length=15)),
            ],
            options={
                'verbose_name': 'Network Settings',
                'verbose_name_plural': 'Network Settings',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('printer', 'Printer'), ('camera', 'Camera'), ('smart_tv', 'Smart TV'), ('iot_device', 'IoT Device'), ('router', 'Router'), ('switch', 'Switch')], default='laptop', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17, unique=True)),
                ('ip_address', models.CharField(help_text='IPv4 or IPv6 address', max_length=45)),
                ('signal_strength', models.IntegerField(default=0, help_text='Signal strength in dBm (-100 to 0)')),
                ('upload_speed', models.FloatField(default=0.0, help_text='Upload speed in Mbps')),
                ('download_speed', models.FloatField(default=0.0, help_text='Download speed in Mbps')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('blocked', 'Blocked')], default='online', max_length=20)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('connected_since', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='network.devicegroup')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_bytes', models.BigIntegerField(default=0, help_text='Upload in bytes')),
                ('download_bytes', models.BigIntegerField(default=0, help_text='Download in bytes')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_logs', to='network.device')),
            ],
            options={
                'verbose_name': 'Traffic Log',
                'verbose_name_plural': 'Traffic Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('alert_type', models.CharField(choices=[('new_device', 'New Device Connected'), ('device_offline', 'Device Offline'), ('high_cpu', 'High CPU Usage'), ('firmware_update', 'Firmware Update Available'), ('weak_password', 'Weak Password'), ('high_bandwidth', 'High Bandwidth Usage')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='network.device')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read'], name='network_ale_is_read_923e9d_idx'), models.Index(fields=['severity'], name='network_ale_severit_2320ba_idx'), models.Index(fields=['alert_type'], name='network_ale_alert_t_effb97_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mac_address'], name='network_dev_mac_add_647fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip_address'], name='network_dev_ip_addr_2fed3f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='network_dev_status_f60d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='network_dev_device__c2f40f_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['device', '-timestamp'], name='network_tra_device__4f3dfe_idx'),
        ),
    ]
