# Generated by Django 6.0.5 on 2026-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Optional bio information'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'Network Administrator'), ('technician', 'Network Technician')], default='technician', max_length=20),
        ),
    ]
